# Generated by Django 4.0 on 2024-12-16 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('telemedicineApp', '0004_appointment1_delete_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment1',
            new_name='Appointment',
        ),
    ]
