# Generated by Django 4.0 on 2024-12-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telemedicineApp', '0005_rename_appointment1_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
